###
Requisicoes de teste do servidor de musica
###

GET http://localhost:3000/musica/0

###

GET http://localhost:3000/musica/0/parte/0 

###
GET http://localhost:3000/musica/0/play

### POSTS

POST http://localhost:3000/musica/0/parte
Content-Type: application/json

{
  "letra": "Parte nova da musica",
  "tag": "teste",
  "tempoEspera": 5000 
}

